spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TomatoMall?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: TomatoMall
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  # 自动更新数据库结构，开发阶段使用，生产环境建议使用none或validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # MySQL数据库的方言
  # 你可以自定义一些其他配置，比如显示SQL
  h2:
    console:
      enabled: true  # 如果你使用H2数据库进行调试时，开启控制台查看数据
server:
  port: 8080
